version: '3.8'

services:
  # Local DynamoDB instance (for manual testing or dev runs)
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    networks:
      - app-network

  # Flask backend
  flask-app:
    build: ../
    container_name: flask-app
    ports:
      - "8084:8084"
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=ap-southeast-1
      - PYTHONPATH=/usr/src/app
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - FLASK_ENV=development
    depends_on:
      - dynamodb-local
    networks:
      - app-network
    command: python app.py

  # Integration test runner
  ticket-booking-pytest:
    build:
      context: ..
      dockerfile: ci/Dockerfile.test
    container_name: flask-tests
    depends_on:
      - flask-app
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=ap-southeast-1
      - PYTHONPATH=/app/src
      - FLASK_ENV=testing
    volumes:
      - ..:/app
    networks:
      - app-network
    command: >
      sh -c "PYTHONPATH=/app pytest -v --disable-warnings --maxfail=1"

networks:
  app-network:
    driver: bridge