FROM python:3.13-slim
WORKDIR /usr/src/app
COPY requirements.txt ./
COPY ci/wait-for-it.sh ./
COPY src/* ./src/
COPY tests/*.py ./tests/
RUN chmod +x wait-for-it.sh
RUN pip install --no-cache-dir -r requirements.txt
CMD ./wait-for-it.sh dynamodb-local:8000 -- python -m pytest